import type { Metadata } from "next";
import "@mantine/core/styles.css";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import HeaderWithSession from "@/components/HeaderWithSession";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import routing from "@/lib/i18n/routing";
import { notFound } from "next/navigation";
import { ModalProvider } from "@/components/modals/ModalManager";
import ToastContainer from "@/components/toast/Toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params:  Promise<{locale: string}>;
}>) {
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }
  return (
    <>
      <NextIntlClientProvider>
        <ModalProvider>
          <HeaderWithSession />
          {children}
          <ToastContainer />
        </ModalProvider>
      </NextIntlClientProvider>
    </>
  );
}
