import type { Metadata } from "next";
import "@mantine/core/styles.css";
import { Geist, Geist_Mono } from "next/font/google";
import { MantineProvider } from "@mantine/core";
import "../globals.css";
import { theme } from "../theme";
import HeaderWithSession from "@/components/HeaderWithSession";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import routing from "@/lib/i18n/routing";
import { notFound } from "next/navigation";
import { ModalProvider } from "@/components/modals/ModalManager";
import ToastContainer from "@/components/toast/Toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params:  Promise<{locale: string}>;
}>) {
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }
  return (
    <html lang={locale}>
      <head>
        <link rel="shortcut icon" href="/favicon.svg" />
        <meta
          name="viewport"
          content="minimum-scale=1, initial-scale=1, width=device-width, user-scalable=no"
        />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <MantineProvider defaultColorScheme="auto" theme={theme}>
          <NextIntlClientProvider>
          <ModalProvider>
            <HeaderWithSession />
            {children}
            <ToastContainer />
          </ModalProvider>
          </NextIntlClientProvider>
        </MantineProvider>
      </body>
    </html>
  );
}
