name: Deploy to OCI

on:
  push:
    branches: [ dev ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Deploy to OCI Instance via SSH
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: 140.238.78.26
        username: opc
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /home/opc/scheduler-app
          git pull origin main
          npm install
          npm run build
          pm2 restart next-app || pm2 start npm --name "next-app" -- start
